defaults:
  - _self_
  - process: process_1
  - model: lgbm-reg
paths:
  raw: ${hydra:runtime.cwd}/data/raw/
  processed: ${hydra:runtime.cwd}/data/processed
  final: ${hydra:runtime.cwd}/data/final
files:
  raw: properties.parquet
  processed: properties_processed.parquet
  final: properties_final.parquet