features:
  used_features: 
    - city
    - type
    - footage
    - doorms
    - garages
    - price
  indep_variables:
    - city
    - type
    - footage
    - doorms
    - garages
  dep_variable:
    - price
thershold:
  type: 
    - Apartamento
    - Casa
    - Cobertura
    - Duplex
    - Studio
  footage: 500
  doorms: 6
  garages: 6
  price: 5_000_000
mlflow:
  experiment: Real_State_Predictions
  tracking_uri: http://127.0.0.1:5000